### ISSUE TITLE
clicking "my notebook" twice seems to break something

### ISSUE THREAD

**Issue by tgrey1** [kunstmusik/csound-notebook#10]
From the main "Welcome to the Csound Notebook!" page, if I click on "My Notebook" it takes me to the proper page showing my two notebooks with one example piece (your recent vox humana example).

If I then click on "My notebook" again, the page breaks... the only listed notebook is "{{notebook.name}}", and the only listed note is "{{note.title}}".  All other fields appear to be blank.

Clicking on "csound notebook" to return to the home page, and then "My notebook" again brings me back to the proper page.

**Comment by kunstmusik** [comment]
Confirmed, that's an odd one.  I'll have to dig in to see what's going on.

**Comment by kunstmusik** [comment]
I've sort of gotten around this by adding the single link to the "other" version of the notebook.  So if you're on the Emscripten version of the notebook, the link up top now switches you to the PNaCl version.  I think this gets around this issue, so I'm closing it now.  Thanks!
