### ISSUE TITLE
ogin asks for user name but actually requires email address

### ISSUE THREAD

**Issue by tgrey1** [kunstmusik/csound-notebook#9]
login fails using the username, which is what the login page asks for.  after a few fails (thought I was mistyping the password) i tried with my email address instead, and that worked for login.

**Comment by kunstmusik** [comment]
The login page here says "Email" here above the email field.  Where is it asking for the username?

**Comment by tgrey1** [comment]
Nowhere, wow I'm dumb today.  After putting in a unsername _AND_ email, my brain tricked me.  I'd _swear_ it asked for username a few minutes ago, but obviously it does not.  Sorry, closing this.

**Comment by kunstmusik** [comment]
No worries, I appreciate that you went through the trouble to file an issue!  Glad this is all good. :)
